version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.9

commands:
  restore_plan:
    parameters:
      target:
        type: enum
        enum: ["mutable", "immutable"]
    steps:
      - restore_cache:
          name: Restore terraform plan result
          key: plan-{{ checksum "environments/<< parameters.target >>/.terraform/plan.txt" }}

  save_plan:
    parameters:
      target:
        type: enum
        enum: ["mutable", "immutable"]
    steps:
      - save_cache:
          name: Cache terraform plan result
          key: plan-{{ checksum "environments/<< parameters.target >>/.terraform/plan.txt" }}

jobs:
  plan:
    executor: aws-cli/default
    docker:
      - image: hashicorp/terraform:<< parameters.terraform-version >>
    parameters:
      terraform-version:
        type: string
        default: latest
      target:
        type: enum
        enum: ["mutable", "immutable"]
      run_save_plan:
        type: boolean
    steps:
      - checkout
      - run:
        name: Execute terraform plan
        command: terraform plan -out .terraform/plan.txt
        working_directory: environments/<< parameters.target >>
      - when:
          condition: << parameters.run_save_plan >>
          steps:
            - save_plan:
                target: << parameters.target >>
  apply:
    executor: aws-cli/default
    docker:
      - image: hashicorp/terraform:<< parameters.terraform-version >>
    parameters:
      terraform-version:
        type: string
        default: latest
      target:
        type: enum
        enum: ["mutable", "immutable"]
      run_restore_plan:
        type: boolean
    steps:
      - checkout
      - when:
          condition: << parameters.run_restore_plan >>
          steps:
            - restore_plan:
                target: << parameters.target >>
            - run:
                name: Execute terraform apply with planfile
                command: terraform apply -input .terraform/plan.txt
                working_directory: environments/<< parameters.target >>
      - unless:
          condition: << parameters.run_restore_plan >>
          steps:
            - run:
                name: Execute terraform apply
                command: terraform apply
                working_directory: environments/<< parameters.target >>

workflows:
  deploy-mutable:
    jobs:
      - plan:
          target: mutable
          run_save_plan: true
      - check-plan:
          type: approval
          requires:
            - plan
      - apply:
          target: mutable
          run_restore_plan: true
          requires:
            - check-plan